# Generated by Django 2.1 on 2019-02-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_action', '0003_auto_20190216_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Image',
            new_name='image',
        ),
    ]
